/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.nprog.zgradeklijent.view.form;


import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;


/**
 *
 * @author Sara
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        super("Projekat PS - Pocetna forma");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        lblUlogovanKorisnik = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miStambenaZajednicaNova = new javax.swing.JMenuItem();
        miStambenaZajednicaPretraga = new javax.swing.JMenuItem();
        miStambenaZajednicaPrikaziSve = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miVlasnikPosebnogDelaNovi = new javax.swing.JMenuItem();
        miVlasnikPosebnogDelaPretraga = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        miSednicaSkupstineNova = new javax.swing.JMenuItem();
        miSednicaSkupstinePretraga = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        jMenu1.setText("Stambena zajednica");

        miStambenaZajednicaNova.setText("Nova");
        jMenu1.add(miStambenaZajednicaNova);

        miStambenaZajednicaPretraga.setText("Pretraga");
        jMenu1.add(miStambenaZajednicaPretraga);

        miStambenaZajednicaPrikaziSve.setText("Prikazi sve");
        jMenu1.add(miStambenaZajednicaPrikaziSve);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vlasnik posebnog dela");

        miVlasnikPosebnogDelaNovi.setText("Novi");
        jMenu2.add(miVlasnikPosebnogDelaNovi);

        miVlasnikPosebnogDelaPretraga.setText("Pretraga");
        jMenu2.add(miVlasnikPosebnogDelaPretraga);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Sednica skupstine");

        miSednicaSkupstineNova.setText("Nova");
        jMenu6.add(miSednicaSkupstineNova);

        miSednicaSkupstinePretraga.setText("Pretraga");
        jMenu6.add(miSednicaSkupstinePretraga);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUlogovanKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 857, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblUlogovanKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUlogovanKorisnik;
    private javax.swing.JMenuItem miSednicaSkupstineNova;
    private javax.swing.JMenuItem miSednicaSkupstinePretraga;
    private javax.swing.JMenuItem miStambenaZajednicaNova;
    private javax.swing.JMenuItem miStambenaZajednicaPretraga;
    private javax.swing.JMenuItem miStambenaZajednicaPrikaziSve;
    private javax.swing.JMenuItem miVlasnikPosebnogDelaNovi;
    private javax.swing.JMenuItem miVlasnikPosebnogDelaPretraga;
    // End of variables declaration//GEN-END:variables

    public void jmiStambenaZajednicaNovaAddActionListener(ActionListener actionListener) {
        miStambenaZajednicaNova.addActionListener(actionListener);
    }

    public void jmiStabenaZajednicaPrikaziSveAddActionListener(ActionListener actionListener) {
        miStambenaZajednicaPrikaziSve.addActionListener(actionListener);
    }

    public void jmiStabenaZajednicaPretragaAddActionListener(ActionListener actionListener) {
        miStambenaZajednicaPretraga.addActionListener(actionListener);
    }

    public void jmiVlasnikPosebnogDelaNoviAddActionListener(ActionListener actionListener) {
        miVlasnikPosebnogDelaNovi.addActionListener(actionListener);
    }

    public void jmiVlasnikPosebnogDelaPretrazivanjeAddActionListener(ActionListener actionListener) {
        miVlasnikPosebnogDelaPretraga.addActionListener(actionListener);
    }

    public void jmiSednicaSkupstineNovaAddActionListener(ActionListener actionListener) {
        miSednicaSkupstineNova.addActionListener(actionListener);
    }

    public void jmiSednicaSkupstinePretrazivanjeAddActionListener(ActionListener actionListener) {
        miSednicaSkupstinePretraga.addActionListener(actionListener);
    }
    public JLabel getLblUlogovanKorisnik() {
        return lblUlogovanKorisnik;
    }

    

}
